name: Backend CI/CD

on:
    push:
        branches: [main]
        paths:
            - "backend/**"
            - ".github/workflows/backend.yml"
    pull_request:
        branches: [main]
        paths:
            - "backend/**"

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: english_app_test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23"

            - name: Install dependencies
              run: |
                  cd backend
                  go mod download

            - name: Run tests
              run: |
                  cd backend
                  go test -v ./...
              env:
                  DB_HOST: localhost
                  DB_PORT: 5432
                  DB_USER: postgres
                  DB_PASSWORD: postgres
                  DB_NAME: english_app_test
                  DB_SSL_MODE: disable

    deploy:
        needs: test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Render
              run: |
                  curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
